# Uncomment this line to define a global platform for your project
# Comment this line if you're not using Swift and don't want to use dynamic frameworks

platform :ios, '9.0'
use_frameworks!

target 'MQDouYuTV' do

pod 'Alamofire'
pod 'Kingfisher'
pod 'MJRefresh'

end
